version: '3.7'
services:
    query-comparison-database:
        image: postgres:11
        container_name: query-comparison-postgres
        restart: always
        ports:
            - '5442:5432'
        deploy:
            resources:
                limits:
                    memory: 128M
                reservations:
                    memory: 128M
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: query-comparison
        volumes:
            - 'query-comparison-postgres-data:/var/lib/postgresql/data'

volumes:
    query-comparison-postgres-data:
        name: query-comparison-postgres-data
        driver: local
